# Generated by Django 4.0.6 on 2022-08-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
