# Generated by Django 4.0.6 on 2022-08-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
